### ISSUE TITLE
Shipping cost rounding difference with Woocommerce 2.2.2. | Wordpress 4.0

### ISSUE THREAD

**Issue by Summer99** [bobbingwide/oik-weightcountry-shipping#1]
Plugin still working, but calculated shipping costs are now slightly different then before.

Configuration:
Taxable (21%)

100|45.4545|1
Was 55.00, now calculated as 54.99

30|12.355|2
Was 14.95, now calculated as 14.96

100|66.1157|2
Was 80.00, now calculated as 80.01

**Comment by bobbingwide** [comment]
hi, super belated response i'm afraid. over in woocommerce's github someone else raised a similar issue. the response was that you cannot have more than 2 decimal places in the rate. so woocommerce is rounding this before applying the tax rate. nothing to do with oik-weightcountry-shipping other than the fact it allows you to type numbers that aren't accepted.

see https://github.com/woothemes/woocommerce/issues/7205
